version: "3.9"
services:
  api:
    build:
      context: .
      command: [ "dotnet", "SkillForge.Api.dll", "--migrate" ]
      dockerfile: SkillForge.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ConnectionStrings__Default=Server=db,1433;Database=SkillForge;User Id=sa;Password=Your_password123;
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Your_password123
    ports:
      - "1433:1433"
